"""tariff_headings, partidas y subpartidas de la LIGIE (ADR 0002)

Revision ID: 9429abec20f3
Revises: 9f5c85042bf1
Create Date: 2026-09-22 23:18:02.421091+00:00

ADR 0002 (22-sep-2026): el motor no encuentra fracciones candidatas porque
la descripción de una fracción no se sostiene sola —«De acero inoxidable.»
no dice de qué— y el sujeto vive en el texto de la partida/subpartida, que
no está en ninguna columna. Tabla NUEVA, no columnas en `tariff_fractions`:
ahí `code` es VARCHAR(8) con `subheading NOT NULL`, y una fila de 4 o 6
dígitos tendría que falsificar la subpartida — con la búsqueda por
`description ILIKE`, el motor podría devolver una partida como si fuera una
fracción real (inventar fundamento, regla 2). Persona 3 detuvo esa carga y
tenía razón.

Nunca entra a `classify_product`: sólo acota candidatas y cita la RGI 1.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9429abec20f3"
down_revision: str | None = "9f5c85042bf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariff_headings",
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("chapter", sa.String(length=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(code) = level", name=op.f("ck_tariff_headings_code_del_largo_del_nivel")
        ),
        sa.CheckConstraint("level IN (4, 6)", name=op.f("ck_tariff_headings_level_valido")),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_tariff_headings_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariff_headings")),
        sa.UniqueConstraint("code", "valid_from", name="uq_tariff_headings_code_valid_from"),
        schema="regulatory",
    )
    op.create_index(
        "ix_tariff_headings_vigencia",
        "tariff_headings",
        ["code", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tariff_headings_vigencia", table_name="tariff_headings", schema="regulatory")
    op.drop_table("tariff_headings", schema="regulatory")
    # ### end Alembic commands ###
