"""shadow_reviews guarda que se comprobo

Revision ID: 9b56789bd5ce
Revises: c6c279b7f115
Create Date: 2026-09-30 23:44:10.423938+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9b56789bd5ce"
down_revision: str | None = "c6c279b7f115"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shadow_reviews",
        sa.Column("verified", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        schema="intelligence",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shadow_reviews", "verified", schema="intelligence")
    # ### end Alembic commands ###
