"""shadow_reviews y shadow_review_id en risk_findings

Revision ID: 040f8397a08a
Revises: a85d3e17c246
Create Date: 2026-09-08 17:45:19.711638+00:00

Persiste `ShadowComparison`: sin esto, `findings.py` no puede distinguir
"no encontré nada" de "no pude revisarlo" y `coverage_known` queda forzado
a `false` siempre. `unverifiable` es `TEXT[]`, no JSONB: en
`core/shadow/types.py` es `tuple[str, ...]`, una lista de cadenas, nada más.
`is_complete` es explícito, no derivado de `unverifiable == '{}'`.

`risk_findings.shadow_review_id` liga cada hallazgo a la corrida que lo
produjo — sin esto, dos auditorías del mismo pedimento mezclan sus
hallazgos. `SET NULL`, no `CASCADE`: si se borra la revisión, el hallazgo
sigue siendo un hecho.

Índice `(pedimento_id, created_at DESC)`: es la consulta que hace
findings.py en cada carga, "la revisión más reciente de este pedimento".

Aprobado por Persona 1, 2026-09-08.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "040f8397a08a"
down_revision: str | None = "a85d3e17c246"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shadow_reviews",
        sa.Column("pedimento_id", sa.Uuid(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("unverifiable", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("engine_version", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pedimento_id"],
            ["operational.pedimentos.id"],
            name=op.f("fk_shadow_reviews_pedimento_id_pedimentos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_shadow_reviews_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shadow_reviews")),
        schema="intelligence",
    )
    op.create_index(
        "ix_shadow_reviews_pedimento",
        "shadow_reviews",
        ["pedimento_id", sa.literal_column("created_at DESC")],
        unique=False,
        schema="intelligence",
    )
    op.add_column(
        "risk_findings",
        sa.Column("shadow_review_id", sa.Uuid(), nullable=True),
        schema="intelligence",
    )
    op.create_foreign_key(
        op.f("fk_risk_findings_shadow_review_id_shadow_reviews"),
        "risk_findings",
        "shadow_reviews",
        ["shadow_review_id"],
        ["id"],
        source_schema="intelligence",
        referent_schema="intelligence",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_risk_findings_shadow_review_id_shadow_reviews"),
        "risk_findings",
        schema="intelligence",
        type_="foreignkey",
    )
    op.drop_column("risk_findings", "shadow_review_id", schema="intelligence")
    op.drop_index("ix_shadow_reviews_pedimento", table_name="shadow_reviews", schema="intelligence")
    op.drop_table("shadow_reviews", schema="intelligence")
    # ### end Alembic commands ###
