"""legal_rule_id en legal_chunks para trazabilidad del RAG

Revision ID: 5443e24b5a3f
Revises: dce813047e49
Create Date: 2026-09-09 21:19:41.305825+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5443e24b5a3f"
down_revision: str | None = "dce813047e49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "legal_chunks", sa.Column("legal_rule_id", sa.Uuid(), nullable=True), schema="regulatory"
    )
    op.create_index(
        "ix_legal_chunks_legal_rule_id",
        "legal_chunks",
        ["legal_rule_id"],
        unique=False,
        schema="regulatory",
    )
    op.create_foreign_key(
        op.f("fk_legal_chunks_legal_rule_id_legal_rules"),
        "legal_chunks",
        "legal_rules",
        ["legal_rule_id"],
        ["id"],
        source_schema="regulatory",
        referent_schema="regulatory",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###

    # Backfill de los chunks ya cargados: liga por la TERNA (documento,
    # artículo, valid_from) — el mismo criterio del UniqueConstraint de
    # legal_rules, así que el cruce es 1 a 1. NO por (documento, artículo)
    # solo: eso sólo funciona mientras exista una única versión cargada de
    # cada artículo (Persona 1, 2026-09-09). Lo que no encuentre match
    # queda NULL — a propósito, no se inventa una fila.
    op.execute("""
        UPDATE regulatory.legal_chunks lc
        SET legal_rule_id = lr.id
        FROM regulatory.legal_rules lr
        WHERE lr.legal_document_id = lc.legal_document_id
          AND lr.rule_number = lc.article
          AND lr.valid_from = lc.valid_from
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_legal_chunks_legal_rule_id_legal_rules"),
        "legal_chunks",
        schema="regulatory",
        type_="foreignkey",
    )
    op.drop_index("ix_legal_chunks_legal_rule_id", table_name="legal_chunks", schema="regulatory")
    op.drop_column("legal_chunks", "legal_rule_id", schema="regulatory")
    # ### end Alembic commands ###
