"""nomenclature_synonyms: kind y answered_by

Revision ID: ffd18b89bac7
Revises: 2fff9e73f31f
Create Date: 2026-10-03 02:43:33.548135+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ffd18b89bac7"
down_revision: str | None = "2fff9e73f31f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nomenclature_synonyms",
        sa.Column(
            "kind",
            sa.Enum("EQUIVALE", "EXCLUYE", name="kind", native_enum=False, create_constraint=True),
            server_default="EQUIVALE",
            nullable=False,
        ),
        schema="regulatory",
    )
    op.add_column(
        "nomenclature_synonyms",
        sa.Column("answered_by", sa.String(length=64), nullable=True),
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nomenclature_synonyms", "answered_by", schema="regulatory")
    op.drop_column("nomenclature_synonyms", "kind", schema="regulatory")
    # ### end Alembic commands ###
