"""fraction_nom_requirements: Anexo 2.4.1

Revision ID: 439320db3bdf
Revises: ffd18b89bac7
Create Date: 2026-10-05 00:23:11.090773+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "439320db3bdf"
down_revision: str | None = "ffd18b89bac7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fraction_nom_requirements",
        sa.Column("fraction_code", sa.String(length=8), nullable=False),
        sa.Column("nom_code", sa.String(length=48), nullable=False),
        sa.Column("numeral", sa.SmallInteger(), nullable=False),
        sa.Column("scope_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_fraction_nom_requirements_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraction_nom_requirements")),
        sa.UniqueConstraint(
            "fraction_code",
            "nom_code",
            "numeral",
            "valid_from",
            name="uq_fraction_nom_requirements_fila",
        ),
        schema="regulatory",
    )
    op.create_index(
        "ix_fraction_nom_requirements_vigencia",
        "fraction_nom_requirements",
        ["fraction_code", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_fraction_nom_requirements_vigencia",
        table_name="fraction_nom_requirements",
        schema="regulatory",
    )
    op.drop_table("fraction_nom_requirements", schema="regulatory")
    # ### end Alembic commands ###
