"""evidence_kind en evidence_records

Revision ID: 76cde5c401f9
Revises: 45af15b11365
Create Date: 2026-09-07 21:30:45.190502+00:00

`created_by` (VARCHAR(16)) no distingue una norma jurídica recuperada de un
precedente de CBP/EBTI — y esa distinción es justo lo que impide que un caso
extranjero se lea como fundamento mexicano. `core/evidence/kinds.py` ya
produce `evidence_kind` en `to_record_fields()`; solo faltaba la columna.

Nullable: las filas existentes no lo tienen y no se rellenan con un valor
inventado. Aprobado por Persona 1 como cambio al Canonical Model.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "76cde5c401f9"
down_revision: str | None = "45af15b11365"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evidence_records",
        sa.Column(
            "evidence_kind",
            sa.Enum(
                "LEGAL_SOURCE",
                "MODEL_OUTPUT",
                "DETERMINISTIC",
                "HUMAN",
                "COMPARABLE",
                name="evidence_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        schema="intelligence",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evidence_records", "evidence_kind", schema="intelligence")
    # ### end Alembic commands ###
