"""cuota compensatoria: compensatory_duties, pedimento_items cc_amount

Revision ID: 88cd0fb12273
Revises: 8d0c36b5f879
Create Date: 2026-10-06 23:38:15.933668+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "88cd0fb12273"
down_revision: str | None = "8d0c36b5f879"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compensatory_duties",
        sa.Column("origin_country", sa.String(length=2), nullable=False),
        sa.Column("fraction_code", sa.String(length=8), nullable=False),
        sa.Column("exporter_name", sa.Text(), nullable=True),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("rate_currency", sa.String(length=3), nullable=False),
        sa.Column("rate_unit", sa.String(length=8), nullable=False),
        sa.Column("scope_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_compensatory_duties_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compensatory_duties")),
        sa.UniqueConstraint(
            "origin_country",
            "fraction_code",
            "exporter_name",
            "valid_from",
            name="uq_compensatory_duties_origin_fraction_exporter_valid_from",
        ),
        schema="regulatory",
    )
    op.create_index(
        "ix_compensatory_duties_vigencia",
        "compensatory_duties",
        ["origin_country", "fraction_code", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.add_column(
        "pedimento_items",
        sa.Column("cc_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        schema="operational",
    )
    op.add_column(
        "pedimento_items",
        sa.Column("cc_amount_currency", sa.CHAR(length=3), nullable=True),
        schema="operational",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pedimento_items", "cc_amount_currency", schema="operational")
    op.drop_column("pedimento_items", "cc_amount", schema="operational")
    op.drop_index(
        "ix_compensatory_duties_vigencia", table_name="compensatory_duties", schema="regulatory"
    )
    op.drop_table("compensatory_duties", schema="regulatory")
    # ### end Alembic commands ###
