"""nomenclature_synonyms: puente comercial a nomenclatura

Revision ID: 52bf2d4cb8de
Revises: 9b56789bd5ce
Create Date: 2026-10-01 23:38:41.163429+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "52bf2d4cb8de"
down_revision: str | None = "9b56789bd5ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nomenclature_synonyms",
        sa.Column("commercial_term", sa.Text(), nullable=False),
        sa.Column("nomenclature_term", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_nomenclature_synonyms_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nomenclature_synonyms")),
        sa.UniqueConstraint(
            "commercial_term",
            "nomenclature_term",
            "valid_from",
            name="uq_nomenclature_synonyms_par",
        ),
        schema="regulatory",
    )
    op.create_index(
        "ix_nomenclature_synonyms_termino",
        "nomenclature_synonyms",
        ["commercial_term"],
        unique=False,
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_nomenclature_synonyms_termino", table_name="nomenclature_synonyms", schema="regulatory"
    )
    op.drop_table("nomenclature_synonyms", schema="regulatory")
    # ### end Alembic commands ###
