"""unique constraint en legal_rules por documento rule_number valid_from

Revision ID: e27b19c1bb2b
Revises: 4f2e5479db69
Create Date: 2026-09-08 21:34:03.032112+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "e27b19c1bb2b"
down_revision: str | None = "4f2e5479db69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_legal_rules_document_rule_valid_from",
        "legal_rules",
        ["legal_document_id", "rule_number", "valid_from"],
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_legal_rules_document_rule_valid_from",
        "legal_rules",
        schema="regulatory",
        type_="unique",
    )
    # ### end Alembic commands ###
