"""rgi_trace en classification_decisions

Revision ID: a85d3e17c246
Revises: f096199305b8
Create Date: 2026-09-07 23:23:09.561801+00:00

`rgi_path` y `reasoning` ya dicen QUÉ se decidió; nada guardaba CÓMO. Una
entrada por paso del RGI: rule_id, status, reasoning_summary,
candidate_codes, confidence, source_ids, missing_information.

Nullable, sin `server_default`: NULL dice "de esta decisión no conservamos
la traza"; un `[]` diría "no hubo pasos", que sería inventar un hecho que
no ocurrió (Persona 1, 2026-09-08).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a85d3e17c246"
down_revision: str | None = "f096199305b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classification_decisions",
        sa.Column("rgi_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="intelligence",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classification_decisions", "rgi_trace", schema="intelligence")
    # ### end Alembic commands ###
