"""opportunity_findings pertenece a una corrida

Sin `shadow_review_id`, cada re-auditoría del mismo pedimento dejaba otra fila
de oportunidad y el tablero las sumaba todas. El pedimento 600010 del corpus
acabó con la MISMA oportunidad **seis veces**, y el «ahorro cuantificado» de la
pantalla contaba ese dinero seis veces: 259 959.97 MXN donde el sobrepago real
del corpus son 27 538.49.

Es el dato de la consola que un cliente querría cobrar, y era el que estaba
multiplicado.

`RiskFinding` tiene esta columna desde el #100, con el mismo razonamiento
escrito: «la exposición de un pedimento no es la suma de las veces que lo hemos
mirado; auditarlo dos veces no lo hace deber el doble». Séptima vez que el
tablero cuenta el histórico donde debía contar el estado vigente.

LAS FILAS EXISTENTES SE QUEDAN EN NULL, Y NO SE CUENTAN

No hay forma honesta de atribuirlas: salieron de corridas distintas y el único
dato que las separaría —cuál— es justo el que no se guardó. Adivinar por fecha
acertaría casi siempre y fallaría en silencio el resto.

Así que se quedan en `NULL` y el tablero NO las cuenta, al contrario que en
`RiskFinding` —donde el nulo sí pasa porque ahí significa «anterior al registro
de corridas», un hecho legítimo—. Aquí significa «se escribió sin la columna
que la identifica», que es otra cosa.

No desaparecen en silencio: el tablero declara cuántas hay en `sin_corrida`.
Quedan fuera del total de forma permanente —no van a recibir un id nunca— y lo
que repuebla la cifra son las filas de la siguiente auditoria, que si lo traen.
Asi que el numero se corrige solo aunque estas filas sigan ahi.

No se borra ninguna fila. Una migración que destruye datos para arreglar un
conteo es peor que el conteo.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e118b7bea934"
down_revision: str | None = "1b3088c4f6f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunity_findings",
        sa.Column("shadow_review_id", sa.Uuid(), nullable=True),
        schema="intelligence",
    )
    op.create_foreign_key(
        op.f("fk_opportunity_findings_shadow_review_id_shadow_reviews"),
        "opportunity_findings",
        "shadow_reviews",
        ["shadow_review_id"],
        ["id"],
        source_schema="intelligence",
        referent_schema="intelligence",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_opportunity_findings_shadow_review_id_shadow_reviews"),
        "opportunity_findings",
        schema="intelligence",
        type_="foreignkey",
    )
    op.drop_column("opportunity_findings", "shadow_review_id", schema="intelligence")
    # ### end Alembic commands ###
