"""pedimento_identifiers: label y supuestos_de_aplicacion

Revision ID: d9fc5116df71
Revises: ef28f5c29b00
Create Date: 2026-10-06 20:09:52.558300+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d9fc5116df71"
down_revision: str | None = "ef28f5c29b00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pedimento_identifiers", sa.Column("label", sa.Text(), nullable=True), schema="regulatory"
    )
    op.add_column(
        "pedimento_identifiers",
        sa.Column("supuestos_de_aplicacion", sa.Text(), nullable=True),
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pedimento_identifiers", "supuestos_de_aplicacion", schema="regulatory")
    op.drop_column("pedimento_identifiers", "label", schema="regulatory")
    # ### end Alembic commands ###
