"""specificity en tariff fractions

Revision ID: f096199305b8
Revises: 76cde5c401f9
Create Date: 2026-09-07 21:55:38.498487+00:00

Sin `specificity`, RGI 3 a) no puede desempatar entre subpartidas candidatas
y todo escala a HUMAN_REVIEW_REQUIRED — caso real reportado por Persona 1
contra la partida 8471 (2026-09-07): 5 subpartidas, ninguna más específica.

`server_default="0"` cubre inserciones futuras sin `specificity` explícito,
pero las 1,444 fracciones ya cargadas necesitan su valor real, no el default
plano — de ahí el UPDATE con la misma heurística de
`ingestion.snice.tariff.specificity_of` (inlineada aquí a propósito: una
migración no debe depender del código de la aplicación, que puede cambiar
después). 0 catch-all ("Los demás"/"Las demás"), 1 exclusión ("excepto"/
"salvo" otra subpartida), 2 afirmativa sin número, 3 afirmativa con un
umbral numérico concreto — el calificador más específico posible.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f096199305b8"
down_revision: str | None = "76cde5c401f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariff_fractions",
        sa.Column("specificity", sa.Integer(), server_default="0", nullable=False),
        schema="regulatory",
    )
    # ### end Alembic commands ###

    # Backfill de las fracciones ya cargadas: el default plano (0) sólo es
    # correcto por casualidad para las que de verdad son catch-all.
    op.execute("""
        UPDATE regulatory.tariff_fractions
        SET specificity = CASE
            WHEN description ~* '^\\s*(los|las)\\s+dem[aá]s' THEN 0
            WHEN description ~* '(excepto|salvo)' THEN 1
            WHEN description ~ '[0-9]' THEN 3
            ELSE 2
        END
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tariff_fractions", "specificity", schema="regulatory")
    # ### end Alembic commands ###
