"""evidence_records: vigencia de la norma citada (valid_from, valid_to)

Revision ID: 4612fe2efe9e
Revises: 9429abec20f3
Create Date: 2026-09-24 15:25:09.087941+00:00

Sin estas dos columnas, `core.evidence.types.Evidence.covers()` trataba
TODA evidencia como si no fuera temporal (nunca restringía fecha), y la
pregunta del §49 "¿cuándo era vigente?" salía siempre "UNKNOWN → vigente"
(`apps/api/routers/evidence.py`) — aunque la norma citada sí tuviera
vigencia conocida al construirse la evidencia (`core.evidence.builder.
legal_source()` ya exige `valid_from` como obligatorio). La lógica de
lectura ya trataba `None` como UNKNOWN, correctamente: el hueco era que la
columna nunca existía para que hubiera algo que leer.

Ambas NULLABLE: no toda evidencia es temporal (una salida de modelo, un
caso comparable, no tienen vigencia propia), y las filas anteriores a esta
migración no tienen una forma honesta de inferir su vigencia en
retrospectiva — `created_at` es cuándo se creó la fila de evidencia, no
cuándo empezó a regir la norma que cita; usarla de respaldo sería inventar
fundamento legal (regla 1 CLAUDE.md). Sin backfill: quedan en NULL,
correctamente leídas como UNKNOWN.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4612fe2efe9e"
down_revision: str | None = "9429abec20f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evidence_records", sa.Column("valid_from", sa.Date(), nullable=True), schema="intelligence"
    )
    op.add_column(
        "evidence_records", sa.Column("valid_to", sa.Date(), nullable=True), schema="intelligence"
    )
    op.create_index(
        "ix_evidence_records_vigencia",
        "evidence_records",
        ["valid_from", "valid_to"],
        unique=False,
        schema="intelligence",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_evidence_records_vigencia", table_name="evidence_records", schema="intelligence"
    )
    op.drop_column("evidence_records", "valid_to", schema="intelligence")
    op.drop_column("evidence_records", "valid_from", schema="intelligence")
    # ### end Alembic commands ###
