"""reform_note en legal_rules para trazabilidad de vigencia

Revision ID: dce813047e49
Revises: 9877c9584a4c
Create Date: 2026-09-09 00:03:13.951452+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dce813047e49"
down_revision: str | None = "9877c9584a4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "legal_rules", sa.Column("reform_note", sa.Text(), nullable=True), schema="regulatory"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("legal_rules", "reform_note", schema="regulatory")
    # ### end Alembic commands ###
