"""indice de vigencia de nomenclature_synonyms

Revision ID: 2fff9e73f31f
Revises: 52bf2d4cb8de
Create Date: 2026-10-01 23:40:22.586073+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "2fff9e73f31f"
down_revision: str | None = "52bf2d4cb8de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_nomenclature_synonyms_termino"),
        table_name="nomenclature_synonyms",
        schema="regulatory",
    )
    op.create_index(
        "ix_nomenclature_synonyms_vigencia",
        "nomenclature_synonyms",
        ["commercial_term", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_nomenclature_synonyms_vigencia", table_name="nomenclature_synonyms", schema="regulatory"
    )
    op.create_index(
        op.f("ix_nomenclature_synonyms_termino"),
        "nomenclature_synonyms",
        ["commercial_term"],
        unique=False,
        schema="regulatory",
    )
    # ### end Alembic commands ###
