"""la decision vigente de cada ficha, sin recorrer la tabla

El tablero, la bandeja y la metrica preguntan lo mismo por cada fila: «¿es esta
la ultima decision de su ficha?», con un max(created_at) correlacionado por
product_dna_id. No habia indice por esa columna, asi que cada pregunta recorria
la tabla entera.

Medido el 6-oct con 5 902 decisiones:

    un solo predicado     13.8 s   (5 902 recorridos completos)
    GET /dashboard        54   s   la primera pantalla de la demo
    GET /review            5.3 s

Crece con el uso, no con el corpus: cada reclasificacion conserva la decision
anterior y añade 181 filas. Con datos reales y meses de operacion habria sido
peor.

Solo un indice. No toca datos y es reversible.

Revision ID: cf43374650ac
Revises: ef28f5c29b00
Create Date: 2026-10-06 20:18:48.424218+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "cf43374650ac"
down_revision: str | None = "ef28f5c29b00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_classification_decisions_ficha_reciente",
        "classification_decisions",
        ["product_dna_id", "created_at"],
        unique=False,
        schema="intelligence",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_classification_decisions_ficha_reciente",
        table_name="classification_decisions",
        schema="intelligence",
    )
    # ### end Alembic commands ###
