"""pedimento_identifiers: Apendice 8 del Anexo 22

Revision ID: 16368c5161d1
Revises: 4612fe2efe9e
Create Date: 2026-09-29 22:56:41.498414+00:00

`core/shadow` declara `required_identifiers` en `None` siempre -- "el
Apéndice 8 del Anexo 22, el catálogo de identificadores, está pendiente de
cargar" -- porque esta tabla no existía. Sólo `code` + `level` (nivel
G/P, cuando el documento lo trae -- 10 de 174 no lo traen): la descripción
corta de cada clave y sus "Supuestos de Aplicación"/"Complemento 1-3" se
envuelven en el layout de 6 columnas del PDF mezclados con la fila
siguiente, sin separador confiable -- mismo motivo que dejó a
`pedimento_claves.label` sin cargar (Apéndice 2, ver su propio docstring).

`(code, level, valid_from)` como llave, no `code` solo: el mismo código se
repite con nivel distinto y significado distinto (p. ej. "CF" nivel G es
"Registro ante la Secretaría...", "CF" nivel P es "Preferencia...") --
verificado contra las 174 entradas reales del documento, sin colisiones.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "16368c5161d1"
down_revision: str | None = "4612fe2efe9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pedimento_identifiers",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("level", sa.String(length=1), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_pedimento_identifiers_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedimento_identifiers")),
        sa.UniqueConstraint(
            "code", "level", "valid_from", name="uq_pedimento_identifiers_code_level_valid_from"
        ),
        schema="regulatory",
    )
    op.create_index(
        "ix_pedimento_identifiers_vigencia",
        "pedimento_identifiers",
        ["code", "level", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_pedimento_identifiers_vigencia", table_name="pedimento_identifiers", schema="regulatory"
    )
    op.drop_table("pedimento_identifiers", schema="regulatory")
    # ### end Alembic commands ###
