"""catalogos de referencia del anexo 22

Revision ID: 4f2e5479db69
Revises: 040f8397a08a
Create Date: 2026-09-08 19:07:14.547361+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4f2e5479db69"
down_revision: str | None = "040f8397a08a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customs_offices",
        sa.Column("aduana", sa.String(length=2), nullable=False),
        sa.Column("seccion", sa.String(length=2), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_customs_offices_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customs_offices")),
        sa.UniqueConstraint("aduana", "seccion", name="uq_customs_offices_aduana_seccion"),
        schema="regulatory",
    )
    op.create_index(
        "ix_customs_offices_vigencia",
        "customs_offices",
        ["aduana", "seccion", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.create_table(
        "non_tariff_regulations",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("issuing_agency", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_non_tariff_regulations_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_non_tariff_regulations")),
        sa.UniqueConstraint("code", "issuing_agency", name="uq_non_tariff_regulations_code_agency"),
        schema="regulatory",
    )
    op.create_index(
        "ix_non_tariff_regulations_vigencia",
        "non_tariff_regulations",
        ["code", "issuing_agency", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.create_table(
        "pedimento_claves",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column(
            "label",
            sa.Text(),
            nullable=True,
            comment="Pendiente de cargar (deuda técnica): el layout de 2 columnas del PDF impide separar la etiqueta de los supuestos de forma confiable. NULL = no cargado, nunca 'sin etiqueta'.",
        ),
        sa.Column(
            "supuestos_de_aplicacion",
            sa.Text(),
            nullable=True,
            comment="Pendiente de cargar (deuda técnica). Toda clave tiene supuestos de aplicación en el documento real: NULL significa inequívocamente 'no cargado', nunca 'no tiene' (Persona 1, 2026-09-08).",
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_pedimento_claves_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedimento_claves")),
        sa.UniqueConstraint("code", name=op.f("uq_pedimento_claves_code")),
        schema="regulatory",
    )
    op.create_index(
        "ix_pedimento_claves_vigencia",
        "pedimento_claves",
        ["code", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.create_table(
        "units_of_measure",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_units_of_measure_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units_of_measure")),
        sa.UniqueConstraint("code", name=op.f("uq_units_of_measure_code")),
        schema="regulatory",
    )
    op.create_index(
        "ix_units_of_measure_vigencia",
        "units_of_measure",
        ["code", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_units_of_measure_vigencia", table_name="units_of_measure", schema="regulatory"
    )
    op.drop_table("units_of_measure", schema="regulatory")
    op.drop_index(
        "ix_pedimento_claves_vigencia", table_name="pedimento_claves", schema="regulatory"
    )
    op.drop_table("pedimento_claves", schema="regulatory")
    op.drop_index(
        "ix_non_tariff_regulations_vigencia",
        table_name="non_tariff_regulations",
        schema="regulatory",
    )
    op.drop_table("non_tariff_regulations", schema="regulatory")
    op.drop_index("ix_customs_offices_vigencia", table_name="customs_offices", schema="regulatory")
    op.drop_table("customs_offices", schema="regulatory")
    # ### end Alembic commands ###
