"""risk_findings dice como se agrega su monto

Dos clases de dinero caben en `impact_amount` y se agregan al contrario. Hasta
hoy el criterio vivia como una lista de tipos de divergencia repetida en tres
sitios -el motor de auditoria, el Espejo y el tablero-, y cada copia podia
derivar de las otras sin que nada fallara: el numero saldria distinto en cada
pantalla y los tres serian defendibles por separado.

    LINEA_COMPLETA     el delta ENTERO de la partida. Una fraccion mal, un
                       valor mal y un origen mal explican el MISMO delta y cada
                       uno lo lleva completo, asi que sumar dos contaria el
                       mismo dinero dos veces: se toma uno.
    UNA_CONTRIBUCION   el error de calculo de UNA contribucion. Un IGI mal
                       calculado y un IVA mal calculado son contribuciones
                       distintas y se deben las dos: se suman. Deduplicarlas
                       con un max() se quedaria con la mayor y perderia la otra.

EL BACKFILL ES SEGURO Y NO ADIVINA

Solo se marcan las filas que YA tienen importe, y para esas el alcance se
deduce del tipo con certeza: hasta esta migracion el unico tipo que llegaba a
llevar monto era la fraccion, porque era el unico que dependia del motor fiscal
y el motor fiscal solo se activaba con una fraccion esperada resuelta.

Las filas sin importe se quedan en NULL: no hay monto que agregar, y ponerles
un alcance afirmaria algo sobre un numero que no existe. El agregador trata
NULL como LINEA_COMPLETA, que es lo que esas filas eran.

Revision ID: 1b3088c4f6f2
Revises: 1e5763ec3eb6
Create Date: 2026-10-05 06:14:16.563870+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1b3088c4f6f2"
down_revision: str | None = "1e5763ec3eb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "risk_findings",
        sa.Column(
            "impact_scope",
            sa.Enum(
                "LINEA_COMPLETA",
                "UNA_CONTRIBUCION",
                name="impact_scope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        schema="intelligence",
    )
    # Solo lo que tiene importe, y solo donde el alcance se deduce del tipo.
    op.execute(
        sa.text("""
        UPDATE intelligence.risk_findings
           SET impact_scope = 'LINEA_COMPLETA'
         WHERE impact_amount IS NOT NULL
           AND finding_type IN ('FRACTION_MISMATCH', 'VALUE_MISMATCH', 'ORIGIN_MISMATCH')
        """)
    )
    op.execute(
        sa.text("""
        UPDATE intelligence.risk_findings
           SET impact_scope = 'UNA_CONTRIBUCION'
         WHERE impact_amount IS NOT NULL
           AND finding_type IN ('IGI_RATE_MISMATCH', 'VAT_MISMATCH')
        """)
    )


def downgrade() -> None:
    op.drop_column("risk_findings", "impact_scope", schema="intelligence")
