"""tabla de chunks del RAG sobre pgvector

Revision ID: 9877c9584a4c
Revises: e27b19c1bb2b
Create Date: 2026-09-08 22:57:01.306133+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "9877c9584a4c"
down_revision: str | None = "e27b19c1bb2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legal_chunks",
        sa.Column("legal_document_id", sa.Uuid(), nullable=False),
        sa.Column("article", sa.String(length=64), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("heading", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["legal_document_id"],
            ["regulatory.legal_documents.id"],
            name=op.f("fk_legal_chunks_legal_document_id_legal_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_legal_chunks_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_chunks")),
        sa.UniqueConstraint(
            "legal_document_id",
            "article",
            "valid_from",
            name="uq_legal_chunks_document_article_valid_from",
        ),
        schema="regulatory",
    )
    op.create_index(
        "ix_legal_chunks_embedding_hnsw",
        "legal_chunks",
        ["embedding"],
        unique=False,
        schema="regulatory",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_legal_chunks_vigencia",
        "legal_chunks",
        ["valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_legal_chunks_vigencia", table_name="legal_chunks", schema="regulatory")
    op.drop_index(
        "ix_legal_chunks_embedding_hnsw",
        table_name="legal_chunks",
        schema="regulatory",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("legal_chunks", schema="regulatory")
    # ### end Alembic commands ###
