"""tariff_heading_groups: niveles de un guion de la LIGIE (ADR 0004)

Revision ID: c6c279b7f115
Revises: 3da38a88cc77
Create Date: 2026-09-30 20:52:43.375138+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c6c279b7f115"
down_revision: str | None = "3da38a88cc77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariff_heading_groups",
        sa.Column("parent_heading_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("description_hash", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_heading_id"],
            ["regulatory.tariff_headings.id"],
            name=op.f("fk_tariff_heading_groups_parent_heading_id_tariff_headings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_tariff_heading_groups_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariff_heading_groups")),
        sa.UniqueConstraint(
            "parent_heading_id",
            "description_hash",
            "valid_from",
            name="uq_tariff_heading_groups_padre_hash_valid_from",
        ),
        schema="regulatory",
    )
    op.create_index(
        "ix_tariff_heading_groups_padre",
        "tariff_heading_groups",
        ["parent_heading_id", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.add_column(
        "tariff_headings", sa.Column("group_id", sa.Uuid(), nullable=True), schema="regulatory"
    )
    op.create_foreign_key(
        op.f("fk_tariff_headings_group_id_tariff_heading_groups"),
        "tariff_headings",
        "tariff_heading_groups",
        ["group_id"],
        ["id"],
        source_schema="regulatory",
        referent_schema="regulatory",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tariff_headings_group_id_tariff_heading_groups"),
        "tariff_headings",
        schema="regulatory",
        type_="foreignkey",
    )
    op.drop_column("tariff_headings", "group_id", schema="regulatory")
    op.drop_index(
        "ix_tariff_heading_groups_padre", table_name="tariff_heading_groups", schema="regulatory"
    )
    op.drop_table("tariff_heading_groups", schema="regulatory")
    # ### end Alembic commands ###
