"""telemetria llm en ai decision mixin

Revision ID: 45af15b11365
Revises: c0e2842d7c2b
Create Date: 2026-09-04 23:13:28.595229+00:00

Puente entre `core/llm/canonical.py` (Persona 3, rama `ulises`) y
`AIDecisionMixin`: seis columnas nuevas —`prompt_id`, `input_tokens`,
`output_tokens`, `latency_ms`, `attempts`, `finish_reason`— en las 4 tablas
que heredan el mixin (`product_dnas`, `classification_decisions`,
`risk_findings`, `opportunity_findings`). Quedan `nullable`: no toda fila
producto de IA nace de una llamada a un LLM (regla determinista del RGI
Engine, corrección humana, importación histórica), y un `NOT NULL` habría
obligado a inventar un valor de relleno.

En su lugar, `ai_call_completeness_check` (nueva, una por tabla) impone la
integridad correcta: si `model_provider` no es NULL, el resto de la
telemetría de esa llamada no puede faltar. Autogenerado y revisado a mano
(§ TAREA_P2): sin `CREATE SCHEMA` porque `intelligence` ya existe desde la
migración anterior.

También cambia el `server_default` de `requires_human_review` de `false` a
`true` en las mismas 4 tablas (decisión de Persona 1): el sistema falla hacia
revisión humana por defecto; bajarlo a `false` es explícito del motor de
clasificación, nunca el punto de partida.

Verificado: `alembic upgrade head && alembic downgrade -1 && alembic upgrade
head` contra Postgres local — limpio, sin rastro al bajar.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "45af15b11365"
down_revision: str | None = "c0e2842d7c2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classification_decisions",
        sa.Column("prompt_id", sa.Text(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "classification_decisions",
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "classification_decisions",
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "classification_decisions",
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "classification_decisions",
        sa.Column("attempts", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "classification_decisions",
        sa.Column("finish_reason", sa.Text(), nullable=True),
        schema="intelligence",
    )
    op.alter_column(
        "classification_decisions",
        "requires_human_review",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
        schema="intelligence",
    )
    op.create_check_constraint(
        op.f("ck_classification_decisions_ai_call_complete"),
        "classification_decisions",
        "model_provider IS NULL OR (model_name IS NOT NULL AND input_tokens IS NOT NULL AND output_tokens IS NOT NULL AND latency_ms IS NOT NULL AND attempts IS NOT NULL)",
        schema="intelligence",
    )
    op.add_column(
        "opportunity_findings",
        sa.Column("prompt_id", sa.Text(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "opportunity_findings",
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "opportunity_findings",
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "opportunity_findings",
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "opportunity_findings",
        sa.Column("attempts", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "opportunity_findings",
        sa.Column("finish_reason", sa.Text(), nullable=True),
        schema="intelligence",
    )
    op.alter_column(
        "opportunity_findings",
        "requires_human_review",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
        schema="intelligence",
    )
    op.create_check_constraint(
        op.f("ck_opportunity_findings_ai_call_complete"),
        "opportunity_findings",
        "model_provider IS NULL OR (model_name IS NOT NULL AND input_tokens IS NOT NULL AND output_tokens IS NOT NULL AND latency_ms IS NOT NULL AND attempts IS NOT NULL)",
        schema="intelligence",
    )
    op.add_column(
        "product_dnas", sa.Column("prompt_id", sa.Text(), nullable=True), schema="intelligence"
    )
    op.add_column(
        "product_dnas",
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "product_dnas",
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "product_dnas", sa.Column("latency_ms", sa.Integer(), nullable=True), schema="intelligence"
    )
    op.add_column(
        "product_dnas", sa.Column("attempts", sa.Integer(), nullable=True), schema="intelligence"
    )
    op.add_column(
        "product_dnas", sa.Column("finish_reason", sa.Text(), nullable=True), schema="intelligence"
    )
    op.alter_column(
        "product_dnas",
        "requires_human_review",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
        schema="intelligence",
    )
    op.create_check_constraint(
        op.f("ck_product_dnas_ai_call_complete"),
        "product_dnas",
        "model_provider IS NULL OR (model_name IS NOT NULL AND input_tokens IS NOT NULL AND output_tokens IS NOT NULL AND latency_ms IS NOT NULL AND attempts IS NOT NULL)",
        schema="intelligence",
    )
    op.add_column(
        "risk_findings", sa.Column("prompt_id", sa.Text(), nullable=True), schema="intelligence"
    )
    op.add_column(
        "risk_findings",
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "risk_findings",
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        schema="intelligence",
    )
    op.add_column(
        "risk_findings", sa.Column("latency_ms", sa.Integer(), nullable=True), schema="intelligence"
    )
    op.add_column(
        "risk_findings", sa.Column("attempts", sa.Integer(), nullable=True), schema="intelligence"
    )
    op.add_column(
        "risk_findings", sa.Column("finish_reason", sa.Text(), nullable=True), schema="intelligence"
    )
    op.alter_column(
        "risk_findings",
        "requires_human_review",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
        schema="intelligence",
    )
    op.create_check_constraint(
        op.f("ck_risk_findings_ai_call_complete"),
        "risk_findings",
        "model_provider IS NULL OR (model_name IS NOT NULL AND input_tokens IS NOT NULL AND output_tokens IS NOT NULL AND latency_ms IS NOT NULL AND attempts IS NOT NULL)",
        schema="intelligence",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_risk_findings_ai_call_complete"),
        "risk_findings",
        schema="intelligence",
        type_="check",
    )
    op.alter_column(
        "risk_findings",
        "requires_human_review",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
        schema="intelligence",
    )
    op.drop_column("risk_findings", "finish_reason", schema="intelligence")
    op.drop_column("risk_findings", "attempts", schema="intelligence")
    op.drop_column("risk_findings", "latency_ms", schema="intelligence")
    op.drop_column("risk_findings", "output_tokens", schema="intelligence")
    op.drop_column("risk_findings", "input_tokens", schema="intelligence")
    op.drop_column("risk_findings", "prompt_id", schema="intelligence")
    op.drop_constraint(
        op.f("ck_product_dnas_ai_call_complete"),
        "product_dnas",
        schema="intelligence",
        type_="check",
    )
    op.alter_column(
        "product_dnas",
        "requires_human_review",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
        schema="intelligence",
    )
    op.drop_column("product_dnas", "finish_reason", schema="intelligence")
    op.drop_column("product_dnas", "attempts", schema="intelligence")
    op.drop_column("product_dnas", "latency_ms", schema="intelligence")
    op.drop_column("product_dnas", "output_tokens", schema="intelligence")
    op.drop_column("product_dnas", "input_tokens", schema="intelligence")
    op.drop_column("product_dnas", "prompt_id", schema="intelligence")
    op.drop_constraint(
        op.f("ck_opportunity_findings_ai_call_complete"),
        "opportunity_findings",
        schema="intelligence",
        type_="check",
    )
    op.alter_column(
        "opportunity_findings",
        "requires_human_review",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
        schema="intelligence",
    )
    op.drop_column("opportunity_findings", "finish_reason", schema="intelligence")
    op.drop_column("opportunity_findings", "attempts", schema="intelligence")
    op.drop_column("opportunity_findings", "latency_ms", schema="intelligence")
    op.drop_column("opportunity_findings", "output_tokens", schema="intelligence")
    op.drop_column("opportunity_findings", "input_tokens", schema="intelligence")
    op.drop_column("opportunity_findings", "prompt_id", schema="intelligence")
    op.drop_constraint(
        op.f("ck_classification_decisions_ai_call_complete"),
        "classification_decisions",
        schema="intelligence",
        type_="check",
    )
    op.alter_column(
        "classification_decisions",
        "requires_human_review",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
        schema="intelligence",
    )
    op.drop_column("classification_decisions", "finish_reason", schema="intelligence")
    op.drop_column("classification_decisions", "attempts", schema="intelligence")
    op.drop_column("classification_decisions", "latency_ms", schema="intelligence")
    op.drop_column("classification_decisions", "output_tokens", schema="intelligence")
    op.drop_column("classification_decisions", "input_tokens", schema="intelligence")
    op.drop_column("classification_decisions", "prompt_id", schema="intelligence")
    # ### end Alembic commands ###
