"""canonical model v0.1

Revision ID: c0e2842d7c2b
Revises:
Create Date: 2026-09-04 20:03:19.406760+00:00

Generada con `alembic revision --autogenerate` contra un PostgreSQL local
vacío (reemplaza la versión anterior, `fe44472c6ada`, que usaba
`Base.metadata.create_all()` — Erick la rechazó con razón: leía los modelos en
tiempo de ejecución, así que nunca quedaba congelada y una 0002 con
`op.add_column` reventaría en cualquier entorno nuevo con `DuplicateColumn`).

Revisado a mano (§ TAREA_P2): el autogenerado no emite `CREATE SCHEMA` aunque
`include_schemas=True` esté en env.py — eso sólo afecta la comparación, no el
DDL. Se añadió a mano para que la migración sea autosuficiente en un entorno
nuevo, sin depender de que ya haya corrido
infrastructure/docker/postgres/init/01_extensions.sql. Todo lo demás
(esquemas por tabla, `ondelete`, tipos, `CHECK` de los enums, los 11 índices)
salió correcto del autogenerado.

Verificado: `alembic upgrade head && alembic downgrade base && alembic
upgrade head` contra Postgres local — limpio, sin rastro al bajar.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSchema

revision: str = "c0e2842d7c2b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Esquemas que tocan las 23 tablas. `raw` (landing de ingestión) llega aparte.
_SCHEMAS: tuple[str, ...] = ("regulatory", "operational", "intelligence")


def upgrade() -> None:
    for schema in _SCHEMAS:
        op.execute(CreateSchema(schema, if_not_exists=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legal_sources",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("authority", sa.Text(), nullable=True),
        sa.Column("jurisdiction", sa.String(length=2), server_default="MX", nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                name="source_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_sources")),
        sa.UniqueConstraint("slug", name=op.f("uq_legal_sources_slug")),
        schema="regulatory",
    )
    op.create_table(
        "evidence_records",
        sa.Column("subject_kind", sa.String(length=48), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("source_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False),
        sa.Column(
            "legal_rule_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False
        ),
        sa.Column(
            "document_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "content_hashes", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("engine_version", sa.Text(), nullable=True),
        sa.Column("model_provider", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=16), server_default="engine", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_evidence_records_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_records")),
        schema="intelligence",
    )
    op.create_index(
        "ix_evidence_records_subject",
        "evidence_records",
        ["subject_kind", "subject_id"],
        unique=False,
        schema="intelligence",
    )
    op.create_table(
        "synthetic_scenarios",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("generator_version", sa.Text(), nullable=True),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_synthetic_scenarios_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_synthetic_scenarios")),
        sa.UniqueConstraint("slug", name=op.f("uq_synthetic_scenarios_slug")),
        schema="operational",
    )
    op.create_table(
        "legal_documents",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("short_name", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "LAW",
                "REGULATION",
                "RULE",
                "ANNEX",
                "TARIFF",
                "DECREE",
                "NOM",
                "TREATY",
                "OTHER",
                name="legal_document_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("document_number", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=2), server_default="es", nullable=False),
        sa.Column("reform_reference", sa.Text(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_legal_documents_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_documents")),
        schema="regulatory",
    )
    op.create_index(
        "ix_legal_documents_vigencia",
        "legal_documents",
        ["short_name", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.create_table(
        "regulatory_events",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authority", sa.Text(), nullable=True),
        sa.Column(
            "event_kind",
            sa.Enum(
                "PUBLICATION",
                "AMENDMENT",
                "REPEAL",
                "ERRATA",
                "NOTICE",
                name="regulatory_event_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("keywords", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "affected_fraction_codes",
            postgresql.ARRAY(sa.String(length=8)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "affected_rule_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_regulatory_events_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regulatory_events")),
        schema="regulatory",
    )
    op.create_index(
        "ix_regulatory_events_vigencia",
        "regulatory_events",
        ["event_kind", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.create_table(
        "clients",
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("rfc", sa.String(length=13), nullable=True),
        sa.Column("country", sa.String(length=2), server_default="MX", nullable=False),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_clients_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_clients_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        schema="operational",
    )
    op.create_table(
        "suppliers",
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("tax_id", sa.String(length=32), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("manufacturer_name", sa.Text(), nullable=True),
        sa.Column("is_manufacturer", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_suppliers_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_suppliers_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        schema="operational",
    )
    op.create_table(
        "legal_rules",
        sa.Column("legal_document_id", sa.Uuid(), nullable=False),
        sa.Column("rule_number", sa.String(length=64), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("heading_text", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("rgi_reference", sa.String(length=8), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["legal_document_id"],
            ["regulatory.legal_documents.id"],
            name=op.f("fk_legal_rules_legal_document_id_legal_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_legal_rules_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_rules")),
        schema="regulatory",
    )
    op.create_index(
        "ix_legal_rules_vigencia",
        "legal_rules",
        ["rule_number", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.create_table(
        "tariff_fractions",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("chapter", sa.String(length=2), nullable=False),
        sa.Column("heading", sa.String(length=4), nullable=False),
        sa.Column("subheading", sa.String(length=6), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=4), nullable=True),
        sa.Column("igi_rate", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("ige_rate", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("legal_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["legal_document_id"],
            ["regulatory.legal_documents.id"],
            name=op.f("fk_tariff_fractions_legal_document_id_legal_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_tariff_fractions_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariff_fractions")),
        sa.UniqueConstraint("code", "valid_from", name="uq_tariff_fractions_code_valid_from"),
        schema="regulatory",
    )
    op.create_index(
        "ix_tariff_fractions_niveles",
        "tariff_fractions",
        ["chapter", "heading", "subheading"],
        unique=False,
        schema="regulatory",
    )
    op.create_index(
        "ix_tariff_fractions_vigencia",
        "tariff_fractions",
        ["code", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.create_table(
        "invoices",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=64), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("incoterm", sa.String(length=3), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("subtotal_amount_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("freight_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("freight_amount_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("insurance_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("insurance_amount_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("total_amount_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["operational.clients.id"],
            name=op.f("fk_invoices_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_invoices_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["operational.suppliers.id"],
            name=op.f("fk_invoices_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_invoices_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint(
            "supplier_id", "invoice_number", name="uq_invoices_supplier_id_invoice_number"
        ),
        schema="operational",
    )
    op.create_table(
        "pedimentos",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("pedimento_number", sa.String(length=21), nullable=False),
        sa.Column("customs_office", sa.String(length=3), nullable=True),
        sa.Column("pedimento_key", sa.String(length=3), nullable=True),
        sa.Column("regime", sa.String(length=3), nullable=True),
        sa.Column(
            "trade_flow",
            sa.Enum(
                "IMPORT", "EXPORT", name="trade_flow", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("operation_date", sa.Date(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), server_default="MXN", nullable=False),
        sa.Column("exchange_rate", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("customs_value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("customs_value_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("total_taxes", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("total_taxes_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("is_simulation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["operational.clients.id"],
            name=op.f("fk_pedimentos_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_pedimentos_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_pedimentos_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedimentos")),
        sa.UniqueConstraint("pedimento_number", name=op.f("uq_pedimentos_pedimento_number")),
        schema="operational",
    )
    op.create_index(
        "ix_pedimentos_operation_date",
        "pedimentos",
        ["operation_date"],
        unique=False,
        schema="operational",
    )
    op.create_table(
        "products",
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("commercial_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("manufacturer_name", sa.Text(), nullable=True),
        sa.Column("country_of_manufacture", sa.String(length=2), nullable=True),
        sa.Column("unit_of_measure", sa.String(length=8), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["operational.clients.id"],
            name=op.f("fk_products_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_products_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["operational.suppliers.id"],
            name=op.f("fk_products_supplier_id_suppliers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_products_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("client_id", "sku", name="uq_products_client_id_sku"),
        schema="operational",
    )
    op.create_table(
        "nicos",
        sa.Column("tariff_fraction_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("full_code", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("correlation", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_nicos_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tariff_fraction_id"],
            ["regulatory.tariff_fractions.id"],
            name=op.f("fk_nicos_tariff_fraction_id_tariff_fractions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nicos")),
        sa.UniqueConstraint("full_code", "valid_from", name="uq_nicos_full_code_valid_from"),
        schema="regulatory",
    )
    op.create_index(
        "ix_nicos_vigencia",
        "nicos",
        ["full_code", "valid_from", "valid_to"],
        unique=False,
        schema="regulatory",
    )
    op.create_table(
        "product_dnas",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "input_kinds",
            postgresql.ARRAY(sa.String(length=16)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "missing_information", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("model_provider", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "requires_human_review", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["intelligence.evidence_records.id"],
            name=op.f("fk_product_dnas_evidence_id_evidence_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["operational.products.id"],
            name=op.f("fk_product_dnas_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_product_dnas_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_product_dnas_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_dnas")),
        sa.UniqueConstraint("product_id", "version", name="uq_product_dnas_product_id_version"),
        schema="intelligence",
    )
    op.create_table(
        "coves",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("cove_number", sa.String(length=32), nullable=False),
        sa.Column("cove_type", sa.String(length=16), nullable=True),
        sa.Column("issued_at", sa.Date(), nullable=True),
        sa.Column("edocument_hash", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["operational.invoices.id"],
            name=op.f("fk_coves_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_coves_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_coves_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coves")),
        sa.UniqueConstraint("cove_number", name=op.f("uq_coves_cove_number")),
        schema="operational",
    )
    op.create_table(
        "invoice_items",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=8), nullable=True),
        sa.Column("country_of_origin", sa.String(length=2), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_price_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("line_total_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["operational.invoices.id"],
            name=op.f("fk_invoice_items_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["operational.products.id"],
            name=op.f("fk_invoice_items_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_invoice_items_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_invoice_items_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_items")),
        sa.UniqueConstraint(
            "invoice_id", "line_number", name="uq_invoice_items_invoice_id_line_number"
        ),
        schema="operational",
    )
    op.create_table(
        "classification_decisions",
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("product_dna_id", sa.Uuid(), nullable=True),
        sa.Column(
            "trade_flow",
            sa.Enum(
                "IMPORT", "EXPORT", name="trade_flow", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("operation_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RESOLVED",
                "INSUFFICIENT_INFORMATION",
                "HUMAN_REVIEW_REQUIRED",
                name="classification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("chapter", sa.String(length=2), nullable=True),
        sa.Column("heading", sa.String(length=4), nullable=True),
        sa.Column("subheading", sa.String(length=6), nullable=True),
        sa.Column("fraction_code", sa.String(length=8), nullable=True),
        sa.Column("nico_code", sa.String(length=2), nullable=True),
        sa.Column("tariff_fraction_id", sa.Uuid(), nullable=True),
        sa.Column("nico_id", sa.Uuid(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column(
            "rgi_path", postgresql.ARRAY(sa.String(length=8)), server_default="{}", nullable=False
        ),
        sa.Column(
            "legal_rule_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False
        ),
        sa.Column("engine_version", sa.Text(), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column(
            "input_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "missing_information", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("estimated_impact_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("estimated_impact_amount_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("model_provider", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "requires_human_review", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["intelligence.evidence_records.id"],
            name=op.f("fk_classification_decisions_evidence_id_evidence_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["nico_id"],
            ["regulatory.nicos.id"],
            name=op.f("fk_classification_decisions_nico_id_nicos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_dna_id"],
            ["intelligence.product_dnas.id"],
            name=op.f("fk_classification_decisions_product_dna_id_product_dnas"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["operational.products.id"],
            name=op.f("fk_classification_decisions_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_classification_decisions_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_classification_decisions_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tariff_fraction_id"],
            ["regulatory.tariff_fractions.id"],
            name=op.f("fk_classification_decisions_tariff_fraction_id_tariff_fractions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_decisions")),
        schema="intelligence",
    )
    op.create_index(
        "ix_classification_decisions_product",
        "classification_decisions",
        ["product_id", "operation_date"],
        unique=False,
        schema="intelligence",
    )
    op.create_table(
        "product_attributes",
        sa.Column("product_dna_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OBSERVED",
                "EXTRACTED",
                "INFERRED",
                "MISSING",
                name="attribute_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("evidence_reference", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evidence_reference"],
            ["intelligence.evidence_records.id"],
            name=op.f("fk_product_attributes_evidence_reference_evidence_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_dna_id"],
            ["intelligence.product_dnas.id"],
            name=op.f("fk_product_attributes_product_dna_id_product_dnas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_product_attributes_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_attributes")),
        sa.UniqueConstraint(
            "product_dna_id", "name", name="uq_product_attributes_product_dna_id_name"
        ),
        schema="intelligence",
    )
    op.create_table(
        "pedimento_items",
        sa.Column("pedimento_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("invoice_item_id", sa.Uuid(), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("declared_fraction_code", sa.String(length=8), nullable=True),
        sa.Column("declared_nico_code", sa.String(length=2), nullable=True),
        sa.Column("tariff_fraction_id", sa.Uuid(), nullable=True),
        sa.Column("nico_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("commercial_unit", sa.String(length=8), nullable=True),
        sa.Column("country_of_origin", sa.String(length=2), nullable=True),
        sa.Column("customs_value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("customs_value_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("igi_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("igi_amount_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("vat_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("vat_amount_currency", sa.CHAR(length=3), nullable=True),
        sa.Column(
            "applied_nom_codes",
            postgresql.ARRAY(sa.String(length=16)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "identifiers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_item_id"],
            ["operational.invoice_items.id"],
            name=op.f("fk_pedimento_items_invoice_item_id_invoice_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["nico_id"],
            ["regulatory.nicos.id"],
            name=op.f("fk_pedimento_items_nico_id_nicos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pedimento_id"],
            ["operational.pedimentos.id"],
            name=op.f("fk_pedimento_items_pedimento_id_pedimentos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["operational.products.id"],
            name=op.f("fk_pedimento_items_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_pedimento_items_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_pedimento_items_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tariff_fraction_id"],
            ["regulatory.tariff_fractions.id"],
            name=op.f("fk_pedimento_items_tariff_fraction_id_tariff_fractions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedimento_items")),
        sa.UniqueConstraint(
            "pedimento_id", "line_number", name="uq_pedimento_items_pedimento_id_line_number"
        ),
        schema="operational",
    )
    op.create_table(
        "classification_candidates",
        sa.Column("classification_decision_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("fraction_code", sa.String(length=8), nullable=True),
        sa.Column("nico_code", sa.String(length=2), nullable=True),
        sa.Column("tariff_fraction_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("is_selected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["classification_decision_id"],
            ["intelligence.classification_decisions.id"],
            name=op.f(
                "fk_classification_candidates_classification_decision_id_classification_decisions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_classification_candidates_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tariff_fraction_id"],
            ["regulatory.tariff_fractions.id"],
            name=op.f("fk_classification_candidates_tariff_fraction_id_tariff_fractions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_candidates")),
        sa.UniqueConstraint(
            "classification_decision_id",
            "rank",
            name="uq_classification_candidates_classification_decision_id_rank",
        ),
        schema="intelligence",
    )
    op.create_table(
        "ground_truth_records",
        sa.Column("pedimento_id", sa.Uuid(), nullable=True),
        sa.Column("pedimento_item_id", sa.Uuid(), nullable=True),
        sa.Column(
            "error_type",
            sa.Enum(
                "WRONG_FRACTION",
                "WRONG_NICO",
                "WRONG_ORIGIN",
                "MISSING_NOM",
                "MISSED_PROSEC",
                "MISSED_PREFERENCE",
                "WRONG_VALUE",
                "MISSING_INCREMENTABLE",
                "WRONG_IDENTIFIER",
                "INCONSISTENT_SKU_CLASSIFICATION",
                name="error_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("original_value", sa.Text(), nullable=True),
        sa.Column("mutated_value", sa.Text(), nullable=True),
        sa.Column(
            "expected_detection", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("expected_field", sa.String(length=64), nullable=True),
        sa.Column(
            "expected_severity",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="gt_expected_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pedimento_id"],
            ["operational.pedimentos.id"],
            name=op.f("fk_ground_truth_records_pedimento_id_pedimentos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pedimento_item_id"],
            ["operational.pedimento_items.id"],
            name=op.f("fk_ground_truth_records_pedimento_item_id_pedimento_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_ground_truth_records_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_ground_truth_records_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ground_truth_records")),
        schema="intelligence",
    )
    op.create_index(
        "ix_ground_truth_records_error_type",
        "ground_truth_records",
        ["error_type"],
        unique=False,
        schema="intelligence",
    )
    op.create_table(
        "opportunity_findings",
        sa.Column("pedimento_id", sa.Uuid(), nullable=True),
        sa.Column("pedimento_item_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("opportunity_type", sa.String(length=48), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "POTENTIAL",
                "VALIDATED",
                "REJECTED",
                name="opportunity_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="POTENTIAL",
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("estimated_saving_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("estimated_saving_amount_currency", sa.CHAR(length=3), nullable=True),
        sa.Column(
            "legal_rule_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False
        ),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("model_provider", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "requires_human_review", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["intelligence.evidence_records.id"],
            name=op.f("fk_opportunity_findings_evidence_id_evidence_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pedimento_id"],
            ["operational.pedimentos.id"],
            name=op.f("fk_opportunity_findings_pedimento_id_pedimentos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pedimento_item_id"],
            ["operational.pedimento_items.id"],
            name=op.f("fk_opportunity_findings_pedimento_item_id_pedimento_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["operational.products.id"],
            name=op.f("fk_opportunity_findings_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_opportunity_findings_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_opportunity_findings_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_findings")),
        schema="intelligence",
    )
    op.create_table(
        "risk_findings",
        sa.Column("pedimento_id", sa.Uuid(), nullable=True),
        sa.Column("pedimento_item_id", sa.Uuid(), nullable=True),
        sa.Column("classification_decision_id", sa.Uuid(), nullable=True),
        sa.Column("finding_type", sa.String(length=48), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column("declared_value", sa.Text(), nullable=True),
        sa.Column("expected_value", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="finding_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("impact_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("impact_amount_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("is_simulation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data_origin",
            sa.Enum(
                "OFFICIAL",
                "PUBLIC",
                "LICENSED",
                "SYNTHETIC",
                "HUMAN_VALIDATED",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("model_provider", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "requires_human_review", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("synthetic_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["classification_decision_id"],
            ["intelligence.classification_decisions.id"],
            name=op.f("fk_risk_findings_classification_decision_id_classification_decisions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["intelligence.evidence_records.id"],
            name=op.f("fk_risk_findings_evidence_id_evidence_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pedimento_id"],
            ["operational.pedimentos.id"],
            name=op.f("fk_risk_findings_pedimento_id_pedimentos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pedimento_item_id"],
            ["operational.pedimento_items.id"],
            name=op.f("fk_risk_findings_pedimento_item_id_pedimento_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["regulatory.legal_sources.id"],
            name=op.f("fk_risk_findings_source_id_legal_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["synthetic_scenario_id"],
            ["operational.synthetic_scenarios.id"],
            name=op.f("fk_risk_findings_synthetic_scenario_id_synthetic_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_findings")),
        schema="intelligence",
    )
    op.create_index(
        "ix_risk_findings_severity",
        "risk_findings",
        ["severity"],
        unique=False,
        schema="intelligence",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_risk_findings_severity", table_name="risk_findings", schema="intelligence")
    op.drop_table("risk_findings", schema="intelligence")
    op.drop_table("opportunity_findings", schema="intelligence")
    op.drop_index(
        "ix_ground_truth_records_error_type",
        table_name="ground_truth_records",
        schema="intelligence",
    )
    op.drop_table("ground_truth_records", schema="intelligence")
    op.drop_table("classification_candidates", schema="intelligence")
    op.drop_table("pedimento_items", schema="operational")
    op.drop_table("product_attributes", schema="intelligence")
    op.drop_index(
        "ix_classification_decisions_product",
        table_name="classification_decisions",
        schema="intelligence",
    )
    op.drop_table("classification_decisions", schema="intelligence")
    op.drop_table("invoice_items", schema="operational")
    op.drop_table("coves", schema="operational")
    op.drop_table("product_dnas", schema="intelligence")
    op.drop_index("ix_nicos_vigencia", table_name="nicos", schema="regulatory")
    op.drop_table("nicos", schema="regulatory")
    op.drop_table("products", schema="operational")
    op.drop_index("ix_pedimentos_operation_date", table_name="pedimentos", schema="operational")
    op.drop_table("pedimentos", schema="operational")
    op.drop_table("invoices", schema="operational")
    op.drop_index(
        "ix_tariff_fractions_vigencia", table_name="tariff_fractions", schema="regulatory"
    )
    op.drop_index("ix_tariff_fractions_niveles", table_name="tariff_fractions", schema="regulatory")
    op.drop_table("tariff_fractions", schema="regulatory")
    op.drop_index("ix_legal_rules_vigencia", table_name="legal_rules", schema="regulatory")
    op.drop_table("legal_rules", schema="regulatory")
    op.drop_table("suppliers", schema="operational")
    op.drop_table("clients", schema="operational")
    op.drop_index(
        "ix_regulatory_events_vigencia", table_name="regulatory_events", schema="regulatory"
    )
    op.drop_table("regulatory_events", schema="regulatory")
    op.drop_index("ix_legal_documents_vigencia", table_name="legal_documents", schema="regulatory")
    op.drop_table("legal_documents", schema="regulatory")
    op.drop_table("synthetic_scenarios", schema="operational")
    op.drop_index(
        "ix_evidence_records_subject", table_name="evidence_records", schema="intelligence"
    )
    op.drop_table("evidence_records", schema="intelligence")
    op.drop_table("legal_sources", schema="regulatory")
    # ### end Alembic commands ###
