/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness. Responde 200 mientras el proceso viva; no toca dependencias.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness. 200 si todo lo configurado responde; 503 si algo está caído.
         *
         *     Un servicio `not_configured` no degrada el resultado: significa que aún no
         *     forma parte del despliegue, no que esté roto.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista los productos del catálogo
         * @description Productos ordenados por SKU, que es lo que el usuario reconoce.
         */
        get: operations["listar_productos_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Un producto del catálogo */
        get: operations["obtener_producto_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/dna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product DNA vigente del producto, con sus atributos
         * @description El DNA marcado como vigente.
         *
         *     Se filtra por `is_current` y no por la versión más alta: un DNA se puede
         *     reemplazar por una revisión humana que no sea la última generada, y la
         *     columna es la que decide cuál rige.
         */
        get: operations["obtener_dna_products__product_id__dna_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clasifica el producto y persiste la decisión
         * @description Corre el motor sobre el Product DNA vigente y guarda el resultado.
         *
         *     Es el único endpoint que escribe. Todo lo demás lee, y por eso este lleva
         *     el commit explícito: la sesión no confirma por su cuenta.
         *
         *     Nunca devuelve 500 por no poder clasificar. Un `INSUFFICIENT_INFORMATION`
         *     con su razón es un resultado legítimo y se persiste igual: saber que el
         *     sistema no pudo, y por qué, vale tanto como el código cuando sí puede.
         */
        post: operations["clasificar_products__product_id__classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista las decisiones de clasificación
         * @description Decisiones, de la más reciente a la más antigua.
         */
        get: operations["listar_decisiones_classifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classifications/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Una decisión con su traza y evidencias */
        get: operations["obtener_decision_classifications__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot/consultas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pregunta al corpus jurídico
         * @description Recupera los pasajes vigentes que hablan de la pregunta.
         *
         *     No redacta una respuesta: devuelve la norma. Ver el módulo para el porqué.
         */
        post: operations["consultar_copilot_consultas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot/cobertura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qué corpus hay detrás del Copilot
         * @description El estado del corpus sin hacer una consulta.
         *
         *     Sirve para que la pantalla pueda decir con qué se va a buscar ANTES de que
         *     alguien escriba la primera pregunta.
         */
        get: operations["cobertura_copilot_cobertura_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hallazgos, del más grave al menos
         * @description Ordenados por severidad en la base, no en el cliente.
         *
         *     Paginar por fecha y reordenar después daría una primera página sin los
         *     hallazgos graves si quedaron fuera del corte.
         */
        get: operations["listar_hallazgos_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/pedimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pedimentos revisables */
        get: operations["listar_pedimentos_findings_pedimentos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/pedimentos/{pedimento_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Un pedimento con sus hallazgos */
        get: operations["obtener_pedimento_findings_pedimentos__pedimento_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedimentos/{pedimento_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revisa el pedimento contra su espejo y persiste los hallazgos
         * @description Corre los cuatro motores sobre el pedimento y guarda el resultado.
         *
         *     Nunca devuelve 500 por no poder revisar una partida. Una partida sin
         *     espejo es un resultado legítimo —va a `unverifiable`— y la revisión se
         *     persiste igual: saber qué NO se revisó es justamente lo que este endpoint
         *     aporta sobre no tener nada.
         */
        post: operations["revisar_pedimentos__pedimento_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dossier §49 de una decisión */
        get: operations["obtener_dossier_evidence__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cifras del sistema
         * @description Todo en una respuesta: un tablero que se pinta a trozos parpadea.
         */
        get: operations["tablero_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Precisión de la clasificación (§39)
         * @description Compara cada veredicto humano con la decisión de máquina de su DNA.
         */
        get: operations["precision_metrics_classification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decisiones esperando revisión humana
         * @description La bandeja, de la más antigua a la más reciente.
         *
         *     Lo más viejo primero a propósito: en una bandeja de trabajo, lo que lleva
         *     más tiempo esperando es lo que más urge, no lo que acaba de llegar.
         */
        get: operations["pendientes_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirma o corrige una decisión
         * @description Registra el veredicto humano SIN borrar el de la máquina.
         *
         *     Crea una decisión nueva marcada `HUMAN_VALIDATED` y saca la original de la
         *     bandeja. Las dos comparten `product_dna_id`, que es lo que permite
         *     emparejarlas para medir precisión (§39).
         */
        post: operations["revisar_review__decision_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedimentos/{pedimento_id}/shadow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * El pedimento declarado frente a su espejo
         * @description Lee la última auditoría. No dispara una nueva.
         */
        get: operations["espejo_pedimentos__pedimento_id__shadow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentinel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vigilancia normativa
         * @description Todo el estado de la vigilancia en una respuesta.
         */
        get: operations["centinela_sentinel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Acierto
         * @description Una métrica de acierto, con lo que hay detrás del porcentaje.
         */
        Acierto: {
            /**
             * Aciertos
             * @default 0
             */
            aciertos: number;
            /**
             * Comparados
             * @default 0
             */
            comparados: number;
            /** Porcentaje */
            porcentaje?: string | null;
        };
        /**
         * AttributeStatus
         * @description §16 maestro — estado de un atributo de Product DNA.
         * @enum {string}
         */
        AttributeStatus: "OBSERVED" | "EXTRACTED" | "INFERRED" | "MISSING";
        /**
         * Auditoria
         * @description Qué se ha revisado de verdad.
         */
        Auditoria: {
            /**
             * Pedimentos
             * @default 0
             */
            pedimentos: number;
            /**
             * Auditados
             * @default 0
             */
            auditados: number;
            /**
             * Sin Auditar
             * @default 0
             */
            sin_auditar: number;
            /**
             * Auditados Completos
             * @default 0
             */
            auditados_completos: number;
        };
        /**
         * Clasificaciones
         * @description Qué ha podido resolver el motor, y qué no.
         */
        Clasificaciones: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Resueltas
             * @default 0
             */
            resueltas: number;
            /**
             * Requieren Revision
             * @default 0
             */
            requieren_revision: number;
            /**
             * Sin Informacion
             * @default 0
             */
            sin_informacion: number;
            /**
             * Con Traza
             * @default 0
             */
            con_traza: number;
        };
        /** ClassificationCandidateRead */
        ClassificationCandidateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /**
             * Classification Decision Id
             * Format: uuid
             */
            classification_decision_id: string;
            /** Rank */
            rank: number;
            /** Fraction Code */
            fraction_code?: string | null;
            /** Nico Code */
            nico_code?: string | null;
            /** Tariff Fraction Id */
            tariff_fraction_id?: string | null;
            /** Confidence */
            confidence?: string | null;
            /** Reasoning */
            reasoning?: string | null;
            /**
             * Is Selected
             * @default false
             */
            is_selected: boolean;
            /** Rejected Reason */
            rejected_reason?: string | null;
        };
        /** ClassificationDecisionRead */
        ClassificationDecisionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Synthetic Scenario Id */
            synthetic_scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
            /** Model Provider */
            model_provider?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Prompt Id */
            prompt_id?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Attempts */
            attempts?: number | null;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Confidence */
            confidence?: string | null;
            /**
             * Requires Human Review
             * @default true
             */
            requires_human_review: boolean;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /** Product Id */
            product_id?: string | null;
            /** Product Dna Id */
            product_dna_id?: string | null;
            trade_flow: components["schemas"]["TradeFlow"];
            /**
             * Operation Date
             * Format: date
             */
            operation_date: string;
            status: components["schemas"]["ClassificationStatus"];
            /** Chapter */
            chapter?: string | null;
            /** Heading */
            heading?: string | null;
            /** Subheading */
            subheading?: string | null;
            /** Fraction Code */
            fraction_code?: string | null;
            /** Nico Code */
            nico_code?: string | null;
            /** Tariff Fraction Id */
            tariff_fraction_id?: string | null;
            /** Nico Id */
            nico_id?: string | null;
            /** Reasoning */
            reasoning?: string | null;
            /** Rgi Path */
            rgi_path?: string[];
            /** Rgi Trace */
            rgi_trace?: {
                [key: string]: unknown;
            }[] | null;
            /** Legal Rule Ids */
            legal_rule_ids?: string[];
            /** Engine Version */
            engine_version?: string | null;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Input Snapshot */
            input_snapshot?: {
                [key: string]: unknown;
            };
            /** Missing Information */
            missing_information?: string[];
            /** Estimated Impact Amount */
            estimated_impact_amount?: string | null;
            /** Estimated Impact Amount Currency */
            estimated_impact_amount_currency?: string | null;
        };
        /**
         * ClassificationDetail
         * @description Una decisión con todo lo necesario para defenderla.
         *
         *     Va todo junto porque quien audita necesita verlo junto: separar los
         *     candidatos o la evidencia en otra petición convertiría "explicar una
         *     decisión" en tres viajes y una reconstrucción manual.
         */
        ClassificationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Synthetic Scenario Id */
            synthetic_scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
            /** Model Provider */
            model_provider?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Prompt Id */
            prompt_id?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Attempts */
            attempts?: number | null;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Confidence */
            confidence?: string | null;
            /**
             * Requires Human Review
             * @default true
             */
            requires_human_review: boolean;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /** Product Id */
            product_id?: string | null;
            /** Product Dna Id */
            product_dna_id?: string | null;
            trade_flow: components["schemas"]["TradeFlow"];
            /**
             * Operation Date
             * Format: date
             */
            operation_date: string;
            status: components["schemas"]["ClassificationStatus"];
            /** Chapter */
            chapter?: string | null;
            /** Heading */
            heading?: string | null;
            /** Subheading */
            subheading?: string | null;
            /** Fraction Code */
            fraction_code?: string | null;
            /** Nico Code */
            nico_code?: string | null;
            /** Tariff Fraction Id */
            tariff_fraction_id?: string | null;
            /** Nico Id */
            nico_id?: string | null;
            /** Reasoning */
            reasoning?: string | null;
            /** Rgi Path */
            rgi_path?: string[];
            /** Rgi Trace */
            rgi_trace?: {
                [key: string]: unknown;
            }[] | null;
            /** Legal Rule Ids */
            legal_rule_ids?: string[];
            /** Engine Version */
            engine_version?: string | null;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Input Snapshot */
            input_snapshot?: {
                [key: string]: unknown;
            };
            /** Missing Information */
            missing_information?: string[];
            /** Estimated Impact Amount */
            estimated_impact_amount?: string | null;
            /** Estimated Impact Amount Currency */
            estimated_impact_amount_currency?: string | null;
            /** Candidates */
            candidates?: components["schemas"]["ClassificationCandidateRead"][];
            /** Evidences */
            evidences?: components["schemas"]["EvidenceRecordRead"][];
            /**
             * Trace Available
             * @default false
             */
            trace_available: boolean;
        };
        /**
         * ClassificationStatus
         * @description §18 maestro — cómo termina una evaluación de clasificación.
         * @enum {string}
         */
        ClassificationStatus: "RESOLVED" | "INSUFFICIENT_INFORMATION" | "HUMAN_REVIEW_REQUIRED";
        /**
         * ClassifyRequest
         * @description Qué hace falta para clasificar, más allá del producto.
         */
        ClassifyRequest: {
            /**
             * Operation Date
             * Format: date
             */
            operation_date: string;
            /**
             * Trade Flow
             * @default IMPORT
             */
            trade_flow: string;
            /** Search Terms */
            search_terms?: string[];
        };
        /**
         * ClassifyResponse
         * @description El resultado, con lo que hay que saber para leerlo.
         */
        ClassifyResponse: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Status */
            status: string;
            /** Fraction Code */
            fraction_code?: string | null;
            /** Confidence */
            confidence?: string | null;
            /** Requires Human Review */
            requires_human_review: boolean;
            /** Trace Steps */
            trace_steps: number;
            /**
             * Legal Refs Used
             * @default 0
             */
            legal_refs_used: number;
            /** Classified Without Legal Notes */
            classified_without_legal_notes: boolean;
            /** Blocked By */
            blocked_by?: string | null;
            /**
             * Modo Busqueda
             * @default TERMINO_Y_VIGENCIA
             */
            modo_busqueda: string;
            /** Degradado Por */
            degradado_por?: string | null;
        };
        /**
         * Consulta
         * @description Una pregunta al corpus, situada en el tiempo.
         */
        Consulta: {
            /** Pregunta */
            pregunta: string;
            /**
             * Fecha
             * @description Fecha de la operación. Decide qué normas podían citarse (§14). Por omisión, hoy — que es lo correcto para una consulta general y lo INCORRECTO para revisar una operación pasada.
             */
            fecha?: string | null;
            /**
             * Limite
             * @default 8
             */
            limite: number;
        };
        /**
         * Dashboard
         * @description El estado del sistema en cifras que se pueden defender.
         */
        Dashboard: {
            clasificaciones?: components["schemas"]["Clasificaciones"];
            auditoria?: components["schemas"]["Auditoria"];
            hallazgos?: components["schemas"]["Hallazgos"];
            oportunidades?: components["schemas"]["Oportunidades"];
            /**
             * Productos
             * @default 0
             */
            productos: number;
            /**
             * Filas Simuladas
             * @default 0
             */
            filas_simuladas: number;
            /**
             * Todo Simulado
             * @default true
             */
            todo_simulado: boolean;
        };
        /**
         * DataOrigin
         * @description §9 maestro — los cinco orígenes de dato. Cerrado.
         * @enum {string}
         */
        DataOrigin: "OFFICIAL" | "PUBLIC" | "LICENSED" | "SYNTHETIC" | "HUMAN_VALIDATED";
        /**
         * DivergenciaRead
         * @description Una diferencia concreta entre lo declarado y lo esperado.
         */
        DivergenciaRead: {
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Finding Type */
            finding_type: string;
            /** Field */
            field?: string | null;
            /** Declared Value */
            declared_value?: string | null;
            /** Expected Value */
            expected_value?: string | null;
            /** Severity */
            severity: string;
            /** Rationale */
            rationale?: string | null;
            /** Impact Amount */
            impact_amount?: string | null;
            /** Impact Amount Currency */
            impact_amount_currency?: string | null;
            /**
             * Is Simulation
             * @default false
             */
            is_simulation: boolean;
        };
        /**
         * DocumentoVigilado
         * @description Un instrumento del corpus y cuánto de él se está vigilando.
         */
        DocumentoVigilado: {
            /** Short Name */
            short_name: string;
            /** Title */
            title: string;
            /** Kind */
            kind: string;
            /** Data Origin */
            data_origin: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Normas
             * @default 0
             */
            normas: number;
            /**
             * Es Fuente Oficial
             * @default false
             */
            es_fuente_oficial: boolean;
        };
        /**
         * DossierRead
         * @description Las diez respuestas, más lo que no se pudo responder.
         */
        DossierRead: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** What */
            what: string;
            /** Why */
            why: string;
            /** Which Rule */
            which_rule: string;
            /** Which Source */
            which_source?: string[];
            /** Source Version */
            source_version?: string[];
            /** Validity */
            validity?: string[];
            /** Data Used */
            data_used?: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence?: string | null;
            /** Money Impact */
            money_impact: string;
            /** Requires Human Review */
            requires_human_review: boolean;
            /** Unanswered */
            unanswered?: string[];
            /**
             * Is Complete
             * @default false
             */
            is_complete: boolean;
            /**
             * Uninterpretable Evidences
             * @default 0
             */
            uninterpretable_evidences: number;
        };
        /**
         * EntradaEnVigor
         * @description Normas que empiezan a regir un día SIN que conste reforma.
         *
         *     No es una ola de reforma y no se presenta como tal. Dos casos:
         *
         *     - `DOCUMENTO_COMPLETO`: el día coincide con la vigencia del documento. Una
         *       resolución anual que se sustituye entera (RGCE 2026) o una tarifa nueva
         *       (LIGIE 2022).
         *     - `SIN_REFORMA_REGISTRADA`: el día no coincide con el del documento y
         *       ninguna nota cita reforma. Puede ser la publicación original de la ley
         *       o una entrada en vigor diferida por transitorio; el corpus no dice
         *       cuál, así que no se afirma ninguna de las dos.
         */
        EntradaEnVigor: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Documento */
            documento: string;
            /** Kind */
            kind: string;
            /** Normas */
            normas: number;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "DOCUMENTO_COMPLETO" | "SIN_REFORMA_REGISTRADA";
            /** Muestra */
            muestra?: string[];
        };
        /**
         * EvidenceKind
         * @description Tipo de evidencia en evidence_records. Espejo de core.evidence.kinds.EvidenceKind.
         * @enum {string}
         */
        EvidenceKind: "LEGAL_SOURCE" | "MODEL_OUTPUT" | "DETERMINISTIC" | "HUMAN" | "COMPARABLE";
        /** EvidenceRecordRead */
        EvidenceRecordRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /** Subject Kind */
            subject_kind?: string | null;
            /** Subject Id */
            subject_id?: string | null;
            /** Summary */
            summary?: string | null;
            /** Source Ids */
            source_ids?: string[];
            /** Legal Rule Ids */
            legal_rule_ids?: string[];
            /** Document Refs */
            document_refs?: {
                [key: string]: unknown;
            }[];
            /** Content Hashes */
            content_hashes?: string[];
            /** Engine Version */
            engine_version?: string | null;
            /** Model Provider */
            model_provider?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * Created By
             * @default engine
             */
            created_by: string;
            evidence_kind?: components["schemas"]["EvidenceKind"] | null;
        };
        /**
         * FindingSeverity
         * @description §21 maestro — severidad de un hallazgo.
         * @enum {string}
         */
        FindingSeverity: "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Hallazgos
         * @description Riesgo detectado, separando lo presentable de lo investigable.
         */
        Hallazgos: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Peor Severidad */
            peor_severidad?: string | null;
            /**
             * Accionables
             * @default 0
             */
            accionables: number;
            /**
             * Solo Investigables
             * @default 0
             */
            solo_investigables: number;
            /** Impacto Cuantificado */
            impacto_cuantificado?: string | null;
            /** Impacto Moneda */
            impacto_moneda?: string | null;
        };
        /**
         * ImpactoEnDecisiones
         * @description Cuánto de lo que ya decidimos se puede contrastar contra la norma.
         */
        ImpactoEnDecisiones: {
            /**
             * Decisiones
             * @default 0
             */
            decisiones: number;
            /**
             * Con Normas Citadas
             * @default 0
             */
            con_normas_citadas: number;
            /**
             * Sin Normas Citadas
             * @default 0
             */
            sin_normas_citadas: number;
            /**
             * Afectadas
             * @default 0
             */
            afectadas: number;
            /**
             * Trazable
             * @default false
             */
            trazable: boolean;
        };
        /**
         * LineaEspejo
         * @description Una partida, con lo declarado y lo que el espejo esperaba.
         */
        LineaEspejo: {
            /** Line Number */
            line_number: number;
            /** Description */
            description: string;
            /** Product Id */
            product_id?: string | null;
            /** Declared Fraction Code */
            declared_fraction_code?: string | null;
            /** Declared Nico Code */
            declared_nico_code?: string | null;
            /** Country Of Origin */
            country_of_origin?: string | null;
            /** Customs Value */
            customs_value?: string | null;
            /** Customs Value Currency */
            customs_value_currency?: string | null;
            /** Expected Fraction Code */
            expected_fraction_code?: string | null;
            /** Estado */
            estado: string;
            /**
             * Verificacion Parcial
             * @default false
             */
            verificacion_parcial: boolean;
            /** Divergencias */
            divergencias?: components["schemas"]["DivergenciaRead"][];
            /** No Verificable Por */
            no_verificable_por?: string[];
            /** Peor Severidad */
            peor_severidad?: string | null;
        };
        /**
         * LivenessResponse
         * @description Respuesta de liveness.
         */
        LivenessResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** App */
            app: string;
            /** Env */
            env: string;
            /** Version */
            version: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * NormaFueraDeVigencia
         * @description Norma con `valid_to`: dejó de estar vigente ese día.
         */
        NormaFueraDeVigencia: {
            /** Rule Number */
            rule_number: string;
            /** Documento */
            documento: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date
             */
            valid_to: string;
            /** Encabezado */
            encabezado?: string | null;
        };
        /**
         * OlaDeReforma
         * @description Un día en que el DOF modificó normas de UN documento.
         *
         *     Sólo cuenta las normas cuya `reform_note` cita ese mismo día («reformado»,
         *     «adicionado» o «derogado» DOF dd-mm-aaaa). No es un evento del DOF: es lo
         *     que el corpus permite deducir sin inventar nada. Si el watcher existiera,
         *     esto se cruzaría con él.
         */
        OlaDeReforma: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Documento */
            documento: string;
            /** Kind */
            kind: string;
            /** Normas */
            normas: number;
            /** Muestra */
            muestra?: string[];
        };
        /**
         * Oportunidades
         * @description Dinero recuperable, que es otra conversación con el cliente.
         */
        Oportunidades: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Ahorro Cuantificado */
            ahorro_cuantificado?: string | null;
            /** Ahorro Moneda */
            ahorro_moneda?: string | null;
        };
        /**
         * Pasaje
         * @description Un fragmento de norma, tal como está en el corpus.
         *
         *     Se devuelve el texto, no un resumen: resumir una norma es donde se pierde
         *     la condición que hacía que no aplicara.
         */
        Pasaje: {
            /** Documento */
            documento: string;
            /** Articulo */
            articulo?: string | null;
            /** Encabezado */
            encabezado?: string | null;
            /** Texto */
            texto: string;
            /** Cita */
            cita: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Data Origin */
            data_origin: string;
            /** Puede Fundamentar */
            puede_fundamentar: boolean;
            /** Url */
            url?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /** Terminos Coincidentes */
            terminos_coincidentes?: string[];
        };
        /**
         * PedimentoEspejo
         * @description El pedimento declarado frente a su espejo (§36).
         */
        PedimentoEspejo: {
            /**
             * Pedimento Id
             * Format: uuid
             */
            pedimento_id: string;
            /** Pedimento Number */
            pedimento_number: string;
            /**
             * Operation Date
             * Format: date
             */
            operation_date: string;
            /** Customs Office */
            customs_office?: string | null;
            /** Data Origin */
            data_origin: string;
            /** Is Simulation */
            is_simulation: boolean;
            revision?: components["schemas"]["RevisionEspejo"] | null;
            /**
             * Revisiones Totales
             * @default 0
             */
            revisiones_totales: number;
            /** Lineas */
            lineas?: components["schemas"]["LineaEspejo"][];
            /**
             * Partidas
             * @default 0
             */
            partidas: number;
            /**
             * Divergentes
             * @default 0
             */
            divergentes: number;
            /**
             * Sin Verificar
             * @default 0
             */
            sin_verificar: number;
            /**
             * Conformes
             * @default 0
             */
            conformes: number;
            /** Exposicion Cuantificada */
            exposicion_cuantificada?: string | null;
            /** Exposicion Moneda */
            exposicion_moneda?: string | null;
            /**
             * Monedas Mezcladas
             * @default false
             */
            monedas_mezcladas: boolean;
            /**
             * Hallazgos Sin Monto
             * @default 0
             */
            hallazgos_sin_monto: number;
            /** Motivos Sin Atribuir */
            motivos_sin_atribuir?: string[];
        };
        /**
         * PedimentoFindings
         * @description Un pedimento con sus hallazgos y, sobre todo, con qué NO se sabe.
         */
        PedimentoFindings: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Synthetic Scenario Id */
            synthetic_scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Pedimento Number */
            pedimento_number: string;
            /** Customs Office */
            customs_office?: string | null;
            /** Pedimento Key */
            pedimento_key?: string | null;
            /** Regime */
            regime?: string | null;
            trade_flow: components["schemas"]["TradeFlow"];
            /**
             * Operation Date
             * Format: date
             */
            operation_date: string;
            /** Entry Date */
            entry_date?: string | null;
            /**
             * Currency
             * @default MXN
             */
            currency: string;
            /** Exchange Rate */
            exchange_rate?: string | null;
            /** Customs Value */
            customs_value?: string | null;
            /** Customs Value Currency */
            customs_value_currency?: string | null;
            /** Total Taxes */
            total_taxes?: string | null;
            /** Total Taxes Currency */
            total_taxes_currency?: string | null;
            /**
             * Is Simulation
             * @default false
             */
            is_simulation: boolean;
            /** Findings */
            findings?: components["schemas"]["RiskFindingRead"][];
            /**
             * Coverage Known
             * @default false
             */
            coverage_known: boolean;
            /** Is Complete */
            is_complete?: boolean | null;
            /** Unverifiable */
            unverifiable?: string[];
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Worst Severity */
            worst_severity?: string | null;
        };
        /** PedimentoRead */
        PedimentoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Synthetic Scenario Id */
            synthetic_scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Pedimento Number */
            pedimento_number: string;
            /** Customs Office */
            customs_office?: string | null;
            /** Pedimento Key */
            pedimento_key?: string | null;
            /** Regime */
            regime?: string | null;
            trade_flow: components["schemas"]["TradeFlow"];
            /**
             * Operation Date
             * Format: date
             */
            operation_date: string;
            /** Entry Date */
            entry_date?: string | null;
            /**
             * Currency
             * @default MXN
             */
            currency: string;
            /** Exchange Rate */
            exchange_rate?: string | null;
            /** Customs Value */
            customs_value?: string | null;
            /** Customs Value Currency */
            customs_value_currency?: string | null;
            /** Total Taxes */
            total_taxes?: string | null;
            /** Total Taxes Currency */
            total_taxes_currency?: string | null;
            /**
             * Is Simulation
             * @default false
             */
            is_simulation: boolean;
        };
        /**
         * PendienteRead
         * @description Una decisión esperando a una persona, con contexto para decidir.
         */
        PendienteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Synthetic Scenario Id */
            synthetic_scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
            /** Model Provider */
            model_provider?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Prompt Id */
            prompt_id?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Attempts */
            attempts?: number | null;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Confidence */
            confidence?: string | null;
            /**
             * Requires Human Review
             * @default true
             */
            requires_human_review: boolean;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /** Product Id */
            product_id?: string | null;
            /** Product Dna Id */
            product_dna_id?: string | null;
            trade_flow: components["schemas"]["TradeFlow"];
            /**
             * Operation Date
             * Format: date
             */
            operation_date: string;
            status: components["schemas"]["ClassificationStatus"];
            /** Chapter */
            chapter?: string | null;
            /** Heading */
            heading?: string | null;
            /** Subheading */
            subheading?: string | null;
            /** Fraction Code */
            fraction_code?: string | null;
            /** Nico Code */
            nico_code?: string | null;
            /** Tariff Fraction Id */
            tariff_fraction_id?: string | null;
            /** Nico Id */
            nico_id?: string | null;
            /** Reasoning */
            reasoning?: string | null;
            /** Rgi Path */
            rgi_path?: string[];
            /** Rgi Trace */
            rgi_trace?: {
                [key: string]: unknown;
            }[] | null;
            /** Legal Rule Ids */
            legal_rule_ids?: string[];
            /** Engine Version */
            engine_version?: string | null;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Input Snapshot */
            input_snapshot?: {
                [key: string]: unknown;
            };
            /** Missing Information */
            missing_information?: string[];
            /** Estimated Impact Amount */
            estimated_impact_amount?: string | null;
            /** Estimated Impact Amount Currency */
            estimated_impact_amount_currency?: string | null;
            /** Producto */
            producto?: string | null;
            /** Sku */
            sku?: string | null;
            /**
             * Pasos Traza
             * @default 0
             */
            pasos_traza: number;
            /** Causas */
            causas?: string[];
            /** Causas Detalle */
            causas_detalle?: string[];
        };
        /**
         * PrecisionClasificacion
         * @description Las cuatro métricas de clasificación del §39.
         */
        PrecisionClasificacion: {
            hs_accuracy?: components["schemas"]["Acierto"];
            fraction_accuracy?: components["schemas"]["Acierto"];
            nico_accuracy?: components["schemas"]["Acierto"];
            /** Human Review Rate */
            human_review_rate?: string | null;
            /**
             * Decisiones Maquina
             * @default 0
             */
            decisiones_maquina: number;
            /**
             * Revisadas
             * @default 0
             */
            revisadas: number;
            /**
             * Pendientes De Revision
             * @default 0
             */
            pendientes_de_revision: number;
            /**
             * Confirmadas
             * @default 0
             */
            confirmadas: number;
            /**
             * Corregidas
             * @default 0
             */
            corregidas: number;
        };
        /** ProductAttributeRead */
        ProductAttributeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /**
             * Product Dna Id
             * Format: uuid
             */
            product_dna_id: string;
            /** Name */
            name: string;
            /** Value */
            value?: string | null;
            /** Unit */
            unit?: string | null;
            status: components["schemas"]["AttributeStatus"];
            /** Confidence */
            confidence?: string | null;
            /** Evidence Reference */
            evidence_reference?: string | null;
        };
        /**
         * ProductDnaDetail
         * @description Un Product DNA con sus atributos.
         *
         *     Van juntos porque nunca se necesitan por separado: un DNA sin sus
         *     atributos no dice nada, y la pantalla tendría que encadenar dos peticiones
         *     para pintar una sola vista.
         */
        ProductDnaDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Synthetic Scenario Id */
            synthetic_scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
            /** Model Provider */
            model_provider?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Prompt Id */
            prompt_id?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Attempts */
            attempts?: number | null;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Confidence */
            confidence?: string | null;
            /**
             * Requires Human Review
             * @default true
             */
            requires_human_review: boolean;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Is Current
             * @default true
             */
            is_current: boolean;
            /** Input Kinds */
            input_kinds?: string[];
            /** Summary */
            summary?: string | null;
            /** Missing Information */
            missing_information?: string[];
            /** Evidence Id */
            evidence_id?: string | null;
            /** Attributes */
            attributes?: components["schemas"]["ProductAttributeRead"][];
        };
        /** ProductRead */
        ProductRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Synthetic Scenario Id */
            synthetic_scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /** Client Id */
            client_id?: string | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /** Sku */
            sku: string;
            /** Commercial Name */
            commercial_name: string;
            /** Description */
            description?: string | null;
            /** Brand */
            brand?: string | null;
            /** Model */
            model?: string | null;
            /** Manufacturer Name */
            manufacturer_name?: string | null;
            /** Country Of Manufacture */
            country_of_manufacture?: string | null;
            /** Unit Of Measure */
            unit_of_measure?: string | null;
        };
        /**
         * ReadinessResponse
         * @description Respuesta de readiness, con el detalle por dependencia.
         */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
            /** Timestamp */
            timestamp: string;
            /** Services */
            services?: {
                [key: string]: components["schemas"]["ServiceCheck"];
            };
        };
        /**
         * Respuesta
         * @description Lo que el corpus tiene sobre la pregunta, y qué se puede hacer con ello.
         */
        Respuesta: {
            /** Pregunta */
            pregunta: string;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Pasajes */
            pasajes?: components["schemas"]["Pasaje"][];
            /**
             * Hay Fundamento
             * @default false
             */
            hay_fundamento: boolean;
            /** Sin Evidencia */
            sin_evidencia?: string | null;
            /**
             * Descartados Por Vigencia
             * @default 0
             */
            descartados_por_vigencia: number;
            /**
             * Descartados Por Origen
             * @default 0
             */
            descartados_por_origen: number;
            /** Terminos Buscados */
            terminos_buscados?: string[];
            /**
             * Modo Busqueda
             * @default TERMINO_Y_VIGENCIA
             */
            modo_busqueda: string;
            /**
             * Busqueda Semantica Disponible
             * @default false
             */
            busqueda_semantica_disponible: boolean;
            /** Degradado Por */
            degradado_por?: string | null;
            /**
             * Chunks Vectorizados
             * @default 0
             */
            chunks_vectorizados: number;
            /**
             * Chunks Totales
             * @default 0
             */
            chunks_totales: number;
            /**
             * Redacta Respuesta
             * @default false
             */
            redacta_respuesta: boolean;
        };
        /**
         * ReviewRequest
         * @description Las tasas de la operación. Todas opcionales; sin ellas no hay monto.
         */
        ReviewRequest: {
            /**
             * Iva Rate
             * @description Fracción, no porcentaje: 0.16, no 16. En región fronteriza 0.08.
             */
            iva_rate?: number | string | null;
            /**
             * Dta Rate
             * @description Derecho de Trámite Aduanero ad valorem. El 8 al millar es 0.008.
             */
            dta_rate?: number | string | null;
            /**
             * Dta Fixed
             * @description Cuota fija de DTA, cuando el régimen la usa en vez de la tasa.
             */
            dta_fixed?: number | string | null;
            /**
             * Ieps Rate
             * @description Sólo en mercancías que lo causan.
             */
            ieps_rate?: number | string | null;
        };
        /**
         * ReviewResponse
         * @description Lo que se encontró, y sobre todo lo que no se pudo comprobar.
         */
        ReviewResponse: {
            /**
             * Review Id
             * Format: uuid
             */
            review_id: string;
            /**
             * Pedimento Id
             * Format: uuid
             */
            pedimento_id: string;
            /** Findings */
            findings: number;
            /** Worst Severity */
            worst_severity?: string | null;
            /** Is Complete */
            is_complete: boolean;
            /** Unverifiable */
            unverifiable?: string[];
            /** Total Exposure */
            total_exposure?: string | null;
            /** Total Recoverable */
            total_recoverable?: string | null;
            /** Currency */
            currency?: string | null;
            /**
             * Mixed Currencies
             * @default false
             */
            mixed_currencies: boolean;
            /**
             * Opportunities
             * @default 0
             */
            opportunities: number;
            /**
             * Quantified Opportunities
             * @default 0
             */
            quantified_opportunities: number;
            /**
             * Is Simulation
             * @default true
             */
            is_simulation: boolean;
            /**
             * Lines Without Expectation
             * @default 0
             */
            lines_without_expectation: number;
            /** Summary */
            summary: string;
        };
        /**
         * RevisionEspejo
         * @description La corrida que se está leyendo.
         */
        RevisionEspejo: {
            /**
             * Review Id
             * Format: uuid
             */
            review_id: string;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Is Complete */
            is_complete: boolean;
            /** Engine Version */
            engine_version?: string | null;
            /** Data Origin */
            data_origin: string;
        };
        /**
         * RevisionRequest
         * @description El veredicto de una persona.
         */
        RevisionRequest: {
            /**
             * Veredicto
             * @enum {string}
             */
            veredicto: "CONFIRMA" | "CORRIGE";
            /** Reviewer */
            reviewer: string;
            /** Fraction Code */
            fraction_code?: string | null;
            /** Nota */
            nota?: string | null;
        };
        /** RevisionResponse */
        RevisionResponse: {
            /**
             * Original Id
             * Format: uuid
             */
            original_id: string;
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /**
             * Veredicto
             * @enum {string}
             */
            veredicto: "CONFIRMA" | "CORRIGE";
            /** Fraction Code */
            fraction_code?: string | null;
        };
        /** RiskFindingRead */
        RiskFindingRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Synthetic Scenario Id */
            synthetic_scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
            /** Model Provider */
            model_provider?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Prompt Id */
            prompt_id?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Attempts */
            attempts?: number | null;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Confidence */
            confidence?: string | null;
            /**
             * Requires Human Review
             * @default true
             */
            requires_human_review: boolean;
            data_origin: components["schemas"]["DataOrigin"];
            /** Source Id */
            source_id?: string | null;
            /** Pedimento Id */
            pedimento_id?: string | null;
            /** Pedimento Item Id */
            pedimento_item_id?: string | null;
            /** Classification Decision Id */
            classification_decision_id?: string | null;
            /** Shadow Review Id */
            shadow_review_id?: string | null;
            /** Finding Type */
            finding_type: string;
            /** Field */
            field?: string | null;
            /** Declared Value */
            declared_value?: string | null;
            /** Expected Value */
            expected_value?: string | null;
            severity: components["schemas"]["FindingSeverity"];
            /** Rationale */
            rationale?: string | null;
            /** Impact Amount */
            impact_amount?: string | null;
            /** Impact Amount Currency */
            impact_amount_currency?: string | null;
            /**
             * Is Simulation
             * @default false
             */
            is_simulation: boolean;
            /** Evidence Id */
            evidence_id?: string | null;
        };
        /**
         * Sentinel
         * @description Estado de la vigilancia normativa a una fecha.
         */
        Sentinel: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Corpus */
            corpus?: components["schemas"]["DocumentoVigilado"][];
            /**
             * Normas Totales
             * @default 0
             */
            normas_totales: number;
            /**
             * Vigentes En Fecha
             * @default 0
             */
            vigentes_en_fecha: number;
            /**
             * Fuera De Vigencia Total
             * @default 0
             */
            fuera_de_vigencia_total: number;
            /** Reformas */
            reformas?: components["schemas"]["OlaDeReforma"][];
            /**
             * Total Olas
             * @default 0
             */
            total_olas: number;
            /** Entradas En Vigor */
            entradas_en_vigor?: components["schemas"]["EntradaEnVigor"][];
            /**
             * Total Entradas En Vigor
             * @default 0
             */
            total_entradas_en_vigor: number;
            /** Fuera De Vigencia */
            fuera_de_vigencia?: components["schemas"]["NormaFueraDeVigencia"][];
            /**
             * Eventos Dof
             * @default 0
             */
            eventos_dof: number;
            /**
             * Vigilancia Automatica
             * @default false
             */
            vigilancia_automatica: boolean;
            impacto?: components["schemas"]["ImpactoEnDecisiones"];
            /**
             * Corpus Sintetico
             * @default 0
             */
            corpus_sintetico: number;
        };
        /**
         * ServiceCheck
         * @description Resultado de sondear una dependencia.
         */
        ServiceCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "down" | "not_configured";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Detail */
            detail?: string | null;
        };
        /**
         * TradeFlow
         * @description Sentido de la operación.
         * @enum {string}
         */
        TradeFlow: "IMPORT" | "EXPORT";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    listar_productos_products_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_producto_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_dna_products__product_id__dna_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDnaDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clasificar_products__product_id__classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_decisiones_classifications_get: {
        parameters: {
            query?: {
                product_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassificationDecisionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_decision_classifications__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassificationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_copilot_consultas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Consulta"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Respuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cobertura_copilot_cobertura_get: {
        parameters: {
            query?: {
                fecha?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Respuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_hallazgos_findings_get: {
        parameters: {
            query?: {
                pedimento_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskFindingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_pedimentos_findings_pedimentos_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedimentoRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_pedimento_findings_pedimentos__pedimento_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedimento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedimentoFindings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisar_pedimentos__pedimento_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedimento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_dossier_evidence__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DossierRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tablero_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    precision_metrics_classification_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrecisionClasificacion"];
                };
            };
        };
    };
    pendientes_review_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendienteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisar_review__decision_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    espejo_pedimentos__pedimento_id__shadow_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedimento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedimentoEspejo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    centinela_sentinel_get: {
        parameters: {
            query?: {
                /** @description Fecha de referencia para la vigencia (§14). Por omisión, hoy. */
                fecha?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sentinel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
